### ISSUE TITLE
1.1.2 version acces token error

### ISSUE THREAD

**Issue by ahmetbasdan** [lil-kita/community-expo-push-notification-server-sdk#10]
I am using 1.1.2 version but response status 500 and take message "ExpoCommunityNotificationServer.Exceptions.InvalidTokenException: Token was not set"

this is my code
![code](https://user-images.githubusercontent.com/18085857/173669814-0f232bd4-8aa1-4d6f-8208-8b527154c206.jpg)

the version i use
![image](https://user-images.githubusercontent.com/18085857/173670068-58cf4fcc-3724-46bb-9155-57afdd4fbbac.png)

response result
![image](https://user-images.githubusercontent.com/18085857/173669945-ccaa9455-1c00-4276-aa9f-ed1f46e47914.png)

**Comment by ahmetbasdan** [comment]
where can i get access token ?

**Comment by lil-kita** [comment]
Hello, to send a notification without token please use `SendPushAsync(pushTicketRequest, false)`  

also, you can create the access token on expo dashboard(Account Settings -> Access Tokens)  
https://expo.dev/accounts/YOUR_USERNAME/settings/access-tokens
